pipeline {
    agent { node { label 'maven' } }
    environment { APP_NAMESPACE = 'ravivittal-s2i' }
    stages {
        stage('Test') {
	    options { timeout(time: 50, unit: 'SECONDS') }
            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}
